### ISSUE TITLE
[TODO] Basic features

### ISSUE THREAD

**Issue by arnaudsomville** [arnaudsomville/recruit_me#1]
Basic features :

- [x] Should be able to send CV
- [x] Should be able to import CV
- [x] Should be able to import cover letter template
- [x] Should be able to modify user information from conf
- [x] Should be able to save state of send CV
- [x] Should be able to send reminder and keep it in memory
